services:

  backstage:
    image: backstage
    build:
      context: .
    ports:
      - ${APP_PORT}:${APP_PORT}
    environment:
      APP_DOMAIN: ${APP_DOMAIN}
      APP_PORT: ${APP_PORT}
      BACKEND_PORT: ${BACKEND_PORT}
      GITHUB_TOKEN: ${GITHUB_TOKEN}
      GITHUB_AUTH_CLIENT_ID: ${GITHUB_AUTH_CLIENT_ID}
      GITHUB_AUTH_CLIENT_SECRET: ${GITHUB_AUTH_CLIENT_SECRET}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
    depends_on:
      - postgres

  postgres:
    image: postgres:17.2-bookworm
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
