apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: example-docs 
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: documentation
  lifecycle: experimental
  owner: group:RnD-Lab
