apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: data-team
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: documentation
  lifecycle: experimental
  owner: group:syntonize
