site_name: Example Techdocs
site_description: Our example docs
plugins:
  - techdocs-core
nav:
  - Home: index.md
  - A Section:
    - Subsection I: subsection_1.md
    - Subsection II: subsection_2.md
