parameters:
- name: app_name
  default: ${{ values.name }}
- name: app_version
  default: 0.0.1

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: TerraformTaskV4@4
    displayName: 'Terraform Init'
    inputs:
      provider: 'aws'
      command: 'init'
      backendServiceAWS: 'aws-practica-terraform'
      backendAWSBucketName: 'eu-west-1-syntonize-aws-baseline-terraform-state-prod'
      backendAWSKey: $${{ values.parameterName }}.tfstate

  - task: TerraformTaskV4@4
    displayName: 'Terraform Plan'
    inputs:
      provider: 'aws'
      command: 'plan'
      commandOptions: '-var "app_name=$${{ values.parameterName }}" -var "app_version=$${{ values.parameterVersion }}" -out=tfplan'
      environmentServiceNameAWS: 'aws-practica-terraform'

  - task: TerraformTaskV4@4
    displayName: 'Terraform Apply'
    inputs:
      provider: 'aws'
      command: 'apply'
      commandOptions: '-auto-approve tfplan'
      environmentServiceNameAWS: 'aws-practica-terraform'
