apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name }}-infra
  annotations:
    dev.azure.com/project-repo: ${{ values.project }}/${{ values.name }}-infra
    dev.azure.com/readme-path: README.md
spec:
  type: service
  owner: group:Infrastructure
  lifecycle: experimental
  system: ${{ values.name }}
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: ${{ values.name }}-lambda
  description: AWS Lambda to run application
spec:
  type: lambda
  owner: group:Infrastructure
  system: ${{ values.name }}
  dependsOn:
    - component:${{ values.name }}-infra
