apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name }}-infra
spec:
  type: service
  owner: group:IT-Security
  lifecycle: experimental
  system: ${{ values.name }}
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: ${{ values.name }}-lambda
  description: AWS Lambda to run application
spec:
  type: lambda
  owner: group:IT-Security
  system: ${{ values.name }}
  dependsOn:
    - component:${{ values.name }}-infra
