---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: ${{ values.name }}
spec:
  owner: group:RnD-Lab
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name }}-app
spec:
  type: service
  owner: group:RnD-Lab
  lifecycle: experimental
  system: ${{ values.name }}
